# Generated by Django 4.0.2 on 2022-02-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_images_listing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
