# Generated by Django 4.0.2 on 2022-02-10 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_user_alter_bid_date_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 9, 21, 2, 22, 568286)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 9, 21, 2, 22, 569284)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 9, 21, 2, 22, 568286)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(max_length=5000, null=True),
        ),
    ]
