# Generated by Django 4.0.2 on 2022-02-28 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_bid_date_alter_comment_date_alter_listing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 20, 14, 40, 24587)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 20, 14, 40, 24587)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 20, 14, 40, 24587)),
        ),
    ]
