# Generated by Django 4.0.3 on 2022-03-11 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_bid_date_alter_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 11, 14, 1, 39, 962214)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 11, 14, 1, 39, 961214)),
        ),
    ]
