# Generated by Django 4.0.3 on 2022-03-20 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_alter_category_options_alter_bid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 20, 13, 7, 38, 210106)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 20, 13, 7, 38, 209139)),
        ),
    ]
